import type { CustomerQuestion, EntityClarityFinding, SalesReadinessState } from '../types/audit'
import { deriveCorroboration } from '../utils/salesReadiness'
interface Props { state: SalesReadinessState; profile: Parameters<typeof deriveCorroboration>[0]; directories: Parameters<typeof deriveCorroboration>[1]; onChange: (state: SalesReadinessState) => void; onAddEntity: (finding: EntityClarityFinding) => void; onAddQuestion: (question: CustomerQuestion) => void }
const entityResults: EntityClarityFinding['result'][] = ['Clear','Partial','Conflicting','Not found','Owner confirmation needed','Unable to verify']
const questionStatuses: CustomerQuestion['status'][] = ['Answered','Partially answered','Not found','Owner confirmation needed','Unable to verify']
export function SalesReadinessPanel({ state, profile, directories, onChange, onAddEntity, onAddQuestion }: Props) {
 const updateEntity=(id:string,patch:Partial<EntityClarityFinding>)=>onChange({...state,entityClarity:state.entityClarity.map(item=>item.id===id?{...item,...patch}:item)})
 const updateQuestion=(id:string,patch:Partial<CustomerQuestion>)=>onChange({...state,customerQuestions:state.customerQuestions.map(item=>item.id===id?{...item,...patch}:item)})
 const corroboration=deriveCorroboration(profile,directories); const entityReviewed=state.entityClarity.filter(x=>x.reviewed).length; const questionReviewed=state.customerQuestions.filter(x=>x.reviewed).length; const corroborationReviewed=corroboration.filter(x=>x.reviewed).length; const total=state.entityClarity.length+state.customerQuestions.length+corroboration.length
 return <section className="panel sales-readiness-panel"><div className="panel-header"><p className="eyebrow">Evidence-backed call preparation</p><h2>Sales Readiness</h2><p>{entityReviewed+questionReviewed+corroborationReviewed} of {total} sales-readiness findings reviewed · Entity {entityReviewed}/{state.entityClarity.length} · Questions {questionReviewed}/{state.customerQuestions.length} · Corroboration {corroborationReviewed}/{corroboration.length}</p></div>
 <section className="voice-section"><h3>Entity Clarity</h3>{state.entityClarity.map(item=><article className="search-query-card" key={item.id}><div className="search-observation-grid"><label>Dimension<input value={item.dimension} readOnly/></label><label>Result<select value={item.result} onChange={e=>updateEntity(item.id,{result:e.target.value as EntityClarityFinding['result']})}>{entityResults.map(x=><option key={x}>{x}</option>)}</select></label><label>Observed value<input value={item.observedValue} onChange={e=>updateEntity(item.id,{observedValue:e.target.value})}/></label><label>Expected value<input value={item.expectedValue} onChange={e=>updateEntity(item.id,{expectedValue:e.target.value})}/></label></div><label>Source evidence<textarea value={item.sourceEvidence} onChange={e=>updateEntity(item.id,{sourceEvidence:e.target.value})}/></label><label>Source URL<input value={item.sourceUrl} onChange={e=>updateEntity(item.id,{sourceUrl:e.target.value})}/></label><label className="checkbox-field"><input type="checkbox" checked={item.reviewed} onChange={e=>updateEntity(item.id,{reviewed:e.target.checked})}/><span>Reviewed finding</span></label><button type="button" disabled={!item.reviewed} onClick={()=>onAddEntity(item)}>Add reviewed finding to Action Plan</button></article>)}</section>
 <section className="voice-section"><h3>Customer-question readiness</h3>{state.customerQuestions.map(item=><article className="search-query-card" key={item.id}><div className="search-observation-grid"><label>Question<input value={item.question} onChange={e=>updateQuestion(item.id,{question:e.target.value})}/></label><label>Status<select value={item.status} onChange={e=>updateQuestion(item.id,{status:e.target.value as CustomerQuestion['status']})}>{questionStatuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Package fit<select value={item.packageFit} onChange={e=>updateQuestion(item.id,{packageFit:e.target.value as CustomerQuestion['packageFit']})}><option value="starter">Starter</option><option value="owner_action">Owner action</option><option value="later">Later</option><option value="excluded">Excluded</option></select></label></div><label>Evidence<textarea value={item.supportingEvidence} onChange={e=>updateQuestion(item.id,{supportingEvidence:e.target.value})}/></label><label>Source URL<input value={item.sourceUrl} onChange={e=>updateQuestion(item.id,{sourceUrl:e.target.value})}/></label><label>Verification<input value={item.verificationMethod} onChange={e=>updateQuestion(item.id,{verificationMethod:e.target.value})}/></label><label className="checkbox-field"><input type="checkbox" checked={item.reviewed} onChange={e=>updateQuestion(item.id,{reviewed:e.target.checked})}/><span>Reviewed finding</span></label><button type="button" disabled={!item.reviewed} onClick={()=>onAddQuestion(item)}>Add reviewed finding to Action Plan</button></article>)}</section>
 <section className="voice-section"><h3>Third-party corroboration</h3>{corroboration.length?corroboration.map(item=><p key={item.id}><strong>{item.destination} — {item.field}: {item.result}</strong><br/>Expected: {item.expectedValue||'Owner confirmation needed'}<br/>Observed: {item.observedValue||'Unable to verify'}<br/>{item.sourceEvidence||'No public evidence note.'}</p>):<p className="empty-state">Public-profile evidence will appear here when recorded in Profile Management.</p>}</section></section>
}
