import { useState } from 'react'
import type { BusinessProfile, BusinessProfileState, SearchDestination, SearchDestinationObservation, SearchVisibilityQuery, SearchVisibilityResult, SearchVisibilityTestState } from '../types/audit'
import { bingSearch, duckDuckGoSearch, googleMapsSearch, googleSearch } from '../utils/links'
import { buildSearchVisibilityQueries, defaultSearchDestinationObservation, normalizeSearchDestinationObservation, normalizeSearchResultTypes, resultTypesForDestination, searchDestinations, searchResultTypeLabel, searchVisibilityResultLabel } from '../utils/searchVisibility'

interface Props { profile: BusinessProfile; profileState: BusinessProfileState; legacyTests: Record<string, SearchVisibilityTestState>; observations: Record<string, Partial<Record<SearchDestination, SearchDestinationObservation>>>; onChange: (query: SearchVisibilityQuery, observation: SearchDestinationObservation) => void; onAddToActionPlan: (query: SearchVisibilityQuery) => void }
const results: SearchVisibilityResult[] = ['not_checked', 'found_prominently', 'found_weak', 'found_conflicting_information', 'not_found', 'unable_to_verify']
const href = (destination: SearchDestination, query: string) => destination === 'Google Search' ? googleSearch(query) : destination === 'Google Maps' ? googleMapsSearch(query) : destination === 'Bing Search' ? bingSearch(query) : destination === 'Apple Maps' ? `https://maps.apple.com/?q=${encodeURIComponent(query)}` : destination === 'Yelp' ? `https://www.yelp.com/search?find_desc=${encodeURIComponent(query)}` : destination === 'Facebook' ? `https://www.facebook.com/search/top?q=${encodeURIComponent(query)}` : destination === 'Instagram' ? `https://www.instagram.com/explore/search/keyword/?q=${encodeURIComponent(query)}` : duckDuckGoSearch(query)
const isCompletedResult = (result: SearchVisibilityResult) => !['not_checked', 'manual_review_needed'].includes(result)

export function SearchVisibilityPanel({ profile, profileState, legacyTests, observations, onChange, onAddToActionPlan }: Props) {
  const [diagnostic, setDiagnostic] = useState(Boolean(legacyTests['search-brand-market'] || observations['search-brand-market']))
  const queries = buildSearchVisibilityQueries(profile, profileState, { includeLocationDiagnostic: diagnostic })
  const patch = (query: SearchVisibilityQuery, destination: SearchDestination, next: Partial<SearchDestinationObservation>) => onChange(query, normalizeSearchDestinationObservation({ ...defaultSearchDestinationObservation(destination, query.query), ...observations[query.id]?.[destination], ...next }))
  return <section className="panel search-visibility-panel">
    <div className="panel-header"><p className="eyebrow">Destination-specific public evidence</p><h2>Public Presence</h2><p>What can a prospective customer publicly find? Record each destination independently; this does not claim owner/admin access.</p></div>
    <div className="search-query-list">{queries.map((query) => <article className="search-query-card" key={query.id}>
      <div className="audit-title-row"><div><p className="fix-area">{query.role}{query.isDiagnostic ? ' · location diagnostic' : ''}</p><h3>{query.query}</h3></div>{query.id === 'search-brand-canonical' && !diagnostic ? <button type="button" className="secondary" onClick={() => setDiagnostic(true)}>Run location diagnostic</button> : null}</div>
      {searchDestinations.map((destination) => { const value = { ...defaultSearchDestinationObservation(destination, query.query), ...observations[query.id]?.[destination] }; const types = resultTypesForDestination(destination); return <details className="destination-observation" key={destination}>
        <summary>{destination} — {searchVisibilityResultLabel(value.overallResult)}</summary>
        <div className="directory-actions"><a href={href(destination, query.query)} target="_blank" rel="noreferrer">Open {destination}</a></div>
        <div className="search-observation-grid"><label>Overall result<select value={value.overallResult} onChange={(event) => { const overallResult = event.target.value as SearchVisibilityResult; patch(query, destination, { overallResult, reviewed: overallResult === 'not_checked' ? false : isCompletedResult(overallResult) ? true : value.reviewed, observedAt: new Date().toISOString(), evidenceKind: overallResult === 'not_found' ? 'absence' : overallResult === 'unable_to_verify' ? 'unable_to_verify' : 'external_observation' }) }}>{results.map((result) => <option key={result} value={result}>{searchVisibilityResultLabel(result)}</option>)}</select></label><label>Observed at<input type="datetime-local" value={value.observedAt.slice(0, 16)} onChange={(event) => patch(query, destination, { observedAt: event.target.value ? new Date(event.target.value).toISOString() : '' })}/></label><label className="checkbox-field"> <input id={`${query.id}-${destination}-reviewed`} type="checkbox" checked={value.reviewed} onChange={(event) => patch(query, destination, { reviewed: event.target.checked })}/><span>Reviewed for Action Plan</span></label></div>
        <fieldset className="result-type-fieldset"><legend>Observed result types</legend>{types.map((type) => <label className="result-type-option" key={type} htmlFor={`${query.id}-${destination}-${type}`}><input id={`${query.id}-${destination}-${type}`} type="checkbox" checked={value.observedResultTypes.includes(type)} onChange={(event) => patch(query, destination, { observedResultTypes: normalizeSearchResultTypes(event.target.checked ? [...value.observedResultTypes, type] : value.observedResultTypes.filter((item) => item !== type)) })}/><span>{searchResultTypeLabel(destination, type)}</span></label>)}</fieldset>
        <div className="directory-row-grid"><label>Evidence notes<textarea value={value.evidenceNotes} onChange={(event) => patch(query, destination, { evidenceNotes: event.target.value })}/></label><label>Competitors observed<textarea value={value.competitorsObserved} onChange={(event) => patch(query, destination, { competitorsObserved: event.target.value })}/></label></div><label className="full-width-label">Recommended action<textarea value={value.recommendedAction} onChange={(event) => patch(query, destination, { recommendedAction: event.target.value })}/></label>
      </details> })}
      <div className="directory-actions"><button type="button" onClick={() => onAddToActionPlan(query)}>Add reviewed primary evidence to Action Plan</button></div>
    </article>)}</div>
  </section>
}
