import type { BusinessProfile, CheckStatus, EvidenceConfidence, VoiceAssistantObservation, VoicePlatformTested } from '../types/audit'
import { buildVoiceReadinessCategories, buildVoiceSourceReadinessGroups, voicePlatforms } from '../utils/voiceReadiness'

interface Props { profile: BusinessProfile; checks: Record<string, CheckStatus>; notes: Record<string, string>; evidenceConfidence: Record<string, EvidenceConfidence>; observations: VoiceAssistantObservation[]; onStatusChange: (id: string, status: CheckStatus) => void; onNoteChange: (id: string, note: string) => void; onEvidenceConfidenceChange: (id: string, confidence: EvidenceConfidence) => void; onObservationChange: (value: VoiceAssistantObservation[]) => void; onAddCategoryToActionPlan: (id: string) => void; onAddObservationToActionPlan: (id: string) => void }
const create = (): VoiceAssistantObservation => ({ id: `voice-observation-${crypto.randomUUID?.() ?? Date.now()}`, assistant: 'Other/manual', deviceOrInterface: '', exactUtterance: '', locationContext: '', loginState: 'unknown', observedAt: new Date().toISOString(), result: 'unable_to_verify', responseTranscript: '', visibleSource: '', evidenceNotes: '', evidenceConfidence: 'manual_needs_confirmation', provenance: 'operator_observation', operatorReviewed: false, recommendedAction: '' })
const label = (result: VoiceAssistantObservation['result']) => result.replace(/_/g, ' ')

export function VoiceReadinessPanel({ profile, checks, notes, observations, onStatusChange, onNoteChange, onObservationChange, onAddCategoryToActionPlan, onAddObservationToActionPlan }: Props) {
  const readiness = [...buildVoiceSourceReadinessGroups(profile, checks), ...buildVoiceReadinessCategories(profile, checks)]
  const update = (id: string, patch: Partial<VoiceAssistantObservation>) => onObservationChange(observations.map((item) => item.id === id ? { ...item, ...patch } : item))
  const coverage = observations.length ? `${observations.filter((item) => item.result !== 'unable_to_verify').length} of ${observations.length} observations recorded` : 'No assistant observations yet — not a failure.'
  return <section className="panel voice-readiness-panel"><div className="panel-header"><p className="eyebrow">Listings and source evidence</p><h2>Entity readiness and optional assistant observations</h2><p>Entity readiness checks public source information such as identity, contact, location, category, website, and core listings. It does not predict what an assistant will answer.</p></div>
    <section className="voice-section"><div className="audit-title-row"><div><p className="fix-area">Entity / listing readiness</p><h3>Source readiness</h3></div><span className="method-pill">{readiness.filter((item) => (checks[item.id] ?? item.suggestedStatus) !== 'unknown').length} checks assessed</span></div><div className="voice-category-grid">{readiness.map((item) => <article className="voice-card" key={item.id}><h3>{item.label}</h3><p>{item.description}</p><select value={checks[item.id] ?? item.suggestedStatus} onChange={(event) => onStatusChange(item.id, event.target.value as CheckStatus)}><option value="unknown">Not checked</option><option value="pass">Pass</option><option value="partial">Partial</option><option value="fail">Fail</option></select><textarea value={notes[item.id] ?? ''} placeholder="Evidence notes" onChange={(event) => onNoteChange(item.id, event.target.value)} /><button type="button" className="secondary" onClick={() => onAddCategoryToActionPlan(item.id)}>Add to Action Plan</button></article>)}</div></section>
    <section className="voice-section"><div className="audit-title-row"><div><p className="fix-area">Optional manual evidence</p><h3>Actual observed consumer-assistant results</h3><p>{coverage}</p></div><button type="button" onClick={() => onObservationChange([...observations, create()])}>Record observed assistant result</button></div>{observations.map((observation) => <article className="search-query-card" key={observation.id}><div className="search-observation-grid"><label>Assistant<select value={observation.assistant} onChange={(event) => update(observation.id, { assistant: event.target.value as VoicePlatformTested })}>{voicePlatforms.map((platform) => <option key={platform}>{platform}</option>)}</select></label><label>Device or interface<input value={observation.deviceOrInterface} onChange={(event) => update(observation.id, { deviceOrInterface: event.target.value })}/></label><label>Login state<select value={observation.loginState} onChange={(event) => update(observation.id, { loginState: event.target.value as VoiceAssistantObservation['loginState'] })}><option>unknown</option><option>logged_in</option><option>logged_out</option></select></label><label>Result<select value={observation.result} onChange={(event) => update(observation.id, { result: event.target.value as VoiceAssistantObservation['result'] })}>{['directly_identified','included_among_options','correct_business_action_available','found_with_inaccurate_facts','wrong_business_selected','not_found','unable_to_verify'].map((result) => <option key={result} value={result}>{label(result as VoiceAssistantObservation['result'])}</option>)}</select></label></div><div className="directory-row-grid"><label>Exact request<textarea value={observation.exactUtterance} onChange={(event) => update(observation.id, { exactUtterance: event.target.value })}/></label><label>Response transcript<textarea value={observation.responseTranscript} onChange={(event) => update(observation.id, { responseTranscript: event.target.value })}/></label><label>Location context<input value={observation.locationContext} onChange={(event) => update(observation.id, { locationContext: event.target.value })}/></label><label>Visible source / notes<textarea value={observation.evidenceNotes} onChange={(event) => update(observation.id, { evidenceNotes: event.target.value })}/></label></div><label className="checkbox-row"><input type="checkbox" checked={observation.operatorReviewed} onChange={(event) => update(observation.id, { operatorReviewed: event.target.checked })}/>Reviewed observation</label><div className="directory-actions"><button type="button" disabled={!observation.operatorReviewed} onClick={() => onAddObservationToActionPlan(observation.id)}>Add reviewed observation to Action Plan</button></div></article>)}</section>
  </section>
}
